### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by trevordmiller** [rizowski/eslint-watch#28]
Your package is great! I'm just running into one issue: when I run my `npm run dev` script, which uses `npm-run-all` I get a `TypeError: undefined is not a function` error, which is preventing my `lint:watch` script from running. I have done some debugging, and everything works as expected running `npm run lint:watch` by itself, or `npm run dev` without the `lint:watch` command...but I don't know how to debug it. Is this a  known issue with `eslint-watch` in the way that it handles npm script arguments or something?

## Related issue

I don't know if this is an issue with `eslint-watch` or `npm-run-all`, so I have posted the issue in both places. I do know that all of my other packages work as expected so something seems to be wrong with either `eslint-watch` or `npm-run-all`.

https://github.com/mysticatea/npm-run-all/issues/9

## Steps to reproduce:

- Clone the project: https://github.com/trevordmiller/npm-run-all-example
- `npm install`
- `npm run lint:watch` runs as expected
- `npm run dev` runs `npm-run-all` which works for everything except for `lint:watch` which is outputting `TypeError: undefined is not a function`

![screen shot 2015-09-03 at 12 56 44 pm](https://cloud.githubusercontent.com/assets/5497885/9667798/4265d996-523b-11e5-8718-028df21e2e9b.png)

---

p.s. I don't understand [why `eslint-watch` hasn't been merged into the core `eslint` package](https://twitter.com/trevordmiller/status/639484847543586816)?

**Comment by rizowski** [comment]
Thanks for posting this, I will take a look at it a little later tonight.
As for your P.S. take a look here: https://github.com/eslint/eslint/issues/2513

**Comment by rizowski** [comment]
@trevordmiller Just a bit of digging I found the culprit. As for why it is throwing, it would seem that having npm-run-all run eslint-watch commands in watch mode, messes with `process.stdin` in some way. Maybe because the process is nested within `npm-run-all`, i'm not a 100% sure. But to resolve this I need a little more information, what version of node are you using?

The only thing this will affect is being able to hit `enter` to rerun the lint. The watch should still work.

**Comment by rizowski** [comment]
@mysticatea This may still be a bug on your side since it seems when `npm-run-all` is running `esw -w` it disables the ability to hit enter and rerun the lint. Look to the above comment for a little context. I'll keep looking into this and see if there is anything I can do. Let me know if you need anything for your side.

**Comment by trevordmiller** [comment]
@rizowski Thanks for looking into it. Yeah, I'm not sure. Basically, I just want to be able to watch my linting (eslint), tests (mocha), and build (babel) at the same time using npm scripts; the `-w` watch command of the `mocha` and `babel` CLIs both work with the packages I have tried for running multiple commands at once (`npm-run-all` and `parallel-shell`) but I'm not sure why eslint doesn't. I'll keep tinkering. Thanks again!

**Comment by mysticatea** [comment]
@rizowski Thank you for investing. I have gotten the cause, thanks to your hint. When `npm-run-all` spawns child processes, it's setting `ignore` to stdin. I changed it to `inherit`, then this error disappeared.

@rizowski @trevordmiller I will release fixed version today.
I apologize for wasting your time.

**Comment by trevordmiller** [comment]
@mysticatea You didn't waste my time - that is great news! Thank you so much :) Thank you @rizowski for your help as well. You both are awesome :+1:

**Comment by rizowski** [comment]
Awesome. Glad I could help. :smiley:
